# Set some variables for convenience
substitutions:
  node_name: supreme
  device_name: Supreme

# Note: this may not be needed if the pull request has been merged.
# Check https://github.com/esphome/esphome/pull/2956 for current status.
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h

esphome:
  name: $node_name
  comment: $device_name

esp32:
  board: esp32dev

wifi:
  ssid: SteepGrades
  password: fuckyou420

# Enable logging
logger:

# Enable wireless updates
ota:

# Enable Home Assistant API
api:
  services:
    # Service to play a song
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
    - service: upload_tft
      then:
        - lambda: 'id(disp1)->upload_tft();'
    - service: send_command
      variables:
        cmd: string
      then:
        - lambda: 'id(disp1).send_command_printf("%s", cmd.c_str());'
        
time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: '*'
        then:
          - lambda: |-
#              auto time_text = id(homeassistant_time).now().strftime("%I:%M%p");
#              id(disp1).set_component_text("home.time", time_text.c_str());

# A reboot button is always useful
button:
  - platform: restart
    name: Restart $device_name
  - platform: template
    name: $device_name TFT Upload
    device_class: update
    on_press:
      - lambda: 'id(disp1).upload_tft();'


# Define some inputs
binary_sensor:
  - platform: gpio
    name: $device_name Left Button
    pin:
      number: 14
      inverted: true
    on_click:
      - switch.toggle: relay_1
    on_release:
      lambda: 'id(disp1).send_command_printf("click wake_button,0");'

  - platform: gpio
    name: $device_name Right Button
    pin:
      number: 27
      inverted: true
    on_click:
      - switch.toggle: relay_2
    on_release:
      lambda: 'id(disp1).send_command_printf("click wake_button,0");'
      
  #House Modes
  - platform: nextion
    name: $device_name Day Mode
    page_id: 0
    component_id: 22
    on_press:
      then:
        - homeassistant.service:
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.day_mode
    
  - platform: nextion
    name: $device_name Evening Mode
    page_id: 0
    component_id: 23
    on_press:
      then:
        - homeassistant.service:
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.evening_mode
    
  - platform: nextion
    name: $device_name Night Mode
    page_id: 0
    component_id: 24
    on_press:
      then:
        - homeassistant.service:
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.night_mode

  - platform: nextion
    name: $device_name LR RGBW
    page_id: 9
    component_id: 9
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.lr_rgbw
              
  - platform: nextion
    name: $device_name LR Fan
    page_id: 0
    component_id: 15
    on_press:
      then:
        - homeassistant.service:
            service: fan.toggle
            data:
              entity_id: fan.living

  - platform: nextion
    name: $device_name LR Overhead
    page_id: 0
    component_id: 16
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.living_overhead

  - platform: nextion
    name: $device_name ZB One
    page_id: 4
    component_id: 5
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.zb_one

  - platform: nextion
    name: $device_name ZB Nine
    page_id: 4
    component_id: 6
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.zb_Nine

  - platform: nextion
    name: $device_name ZB Ten
    page_id: 4
    component_id: 8
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.zb_ten

  - platform: nextion
    name: $device_name ZB Eleven
    page_id: 4
    component_id: 9
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.zb_eleven

  - platform: nextion
    name: $device_name Coffee Table
    page_id: 4
    component_id: 7
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.zb_hexagon_table





sensor:
  - platform: homeassistant # outside temperature
    id: temp_outside
    entity_id: sensor.garden_sensor_temperature

  - platform: wifi_signal
    name: $device_name WiFi Signal
    update_interval: 60s

  - platform: ntc
    id: current_temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: $device_name Temperature

  - platform: resistance
    id: resistance_sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm

  - platform: adc
    id: ntc_source
    pin: 38
    update_interval: 10s
    attenuation: 11db

# Living Room Airthings

  - platform: homeassistant
    id: lr_ar_t
    entity_id: sensor.living_room_temperature
  - platform: homeassistant
    id: lr_ar_h
    entity_id: sensor.living_room_humidity
  - platform: homeassistant
    id: lr_ar_v
    entity_id: sensor.living_room_voc



# Define some outputs
switch:
  # The two relays
  - platform: gpio
    name: $device_name Relay 1
    id: relay_1
    pin:
      number: 22
  - platform: gpio
    name: $device_name Relay 2
    id: relay_2
    pin:
      number: 19

  # Pin 4 always needs to be on to power up the display
  - platform: gpio
    id: screen_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON
    
text_sensor:
  #House Modes
  - platform: homeassistant
    id: day_mode
    entity_id: input_boolean.day_mode

  - platform: homeassistant
    id: evening_mode
    entity_id: input_boolean.evening_mode
    
  - platform: homeassistant
    id: night_mode
    entity_id: input_boolean.night_mode
    
  - platform: homeassistant
    id: weather_symbol
    entity_id: weather.home
 
# LR Lights    
  - platform: homeassistant
    id: zone
    entity_id: light.zb_one

  - platform: homeassistant
    id: znine
    entity_id: light.zb_nine

  - platform: homeassistant
    id: zten
    entity_id: light.zb_ten

  - platform: homeassistant
    id: zeleven
    entity_id: light.zb_eleven

  - platform: homeassistant
    id: zhexagon
    entity_id: light.hexagon_table

  - platform: homeassistant
    id: zoverhead
    entity_id: light.lr_overhead

  - platform: homeassistant
    id: zirror
    entity_id: light.govee_mirror

  - platform: homeassistant
    id: lr_colors
    entity_id: light.lr_rgbw    

  - platform: homeassistant
    id: lr_fan
    entity_id: fan.living
#
number:
  - platform: template
    name: $device_name Brightness
    id: brightness
    entity_category: config
    unit_of_measurement: '%'
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 30
    set_action:
      then:
        - lambda: 'id(disp1).set_backlight_brightness(x/100);'
      
# Configure the internal bleeper
output:
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

# Enable ringtone music support
rtttl:
  id: buzzer
  output: buzzer_out

# Configure UART for communicating with the screen
uart:
  id: tf_uart
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600

# Configure the screen itself
display:
  - platform: nextion
    id: disp1
    uart_id: tf_uart
    tft_url: http://192.168.6.26:8123/local/uploads/LivingRoom.tft
    # A little fun...
    on_setup:
      then:
        - number.set:
            id: brightness
            value: 30

    lambda: |-
    
      int status_lock=0;
      if (id(door_lock).state == "unlocked") {
        status_lock=16;
      } else if (id(door_lock).state == "locked") {
        status_lock=26;
      }
      id(disp1).send_command_printf("lock_b.picc=%i", status_lock);
      id(disp1).send_command_printf("lock_b.picc2=%i", status_lock);
      
      int status_lounge_main=0;
      if (id(lounge_main).state == "off") {
        status_lounge_main=20;
      } else if (id(lounge_main).state == "on") {
        status_lounge_main=27;
      }
      id(disp1).send_command_printf("loungemain_b.picc=%i", status_lounge_main);
      id(disp1).send_command_printf("loungemain.picc2=%i", status_lounge_main);
 # Sun Room
      int status_sr_colors=0;
      if (id(sr_colors).state == "off") {
        status_sr_colors=20;
      } else if (id(sr_colors).state == "on") {
        status_sr_colors=27;
      }
      id(disp1).send_command_printf("sr_colors_b.picc=%i", status_sr_colors);
      id(disp1).send_command_printf("sr_colors_b.picc2=%i", status_sr_colors);  
 # Kitchen #####################################################################################################

      int status_kd_colors=0;
      if (id(kd_colors).state == "off") {
        status_kd_colors=20;
      } else if (id(kd_colors).state == "on") {
        status_kd_colors=27;
      }
      id(disp1).send_command_printf("kd_colors_b.picc=%i", status_kd_colors);
      id(disp1).send_command_printf("kd_colors_b.picc2=%i", status_kd_colors);  

      int status_kd_fan=0;
      if (id(kd_fan).state == "off") {
        status_kd_fan=20;
      } else if (id(kd_fan).state == "on") {
        status_kd_fan=27;
      }
      id(disp1).send_command_printf("kd_fan_b.picc=%i", status_kd_fan);
      id(disp1).send_command_printf("kd_fan_b.picc2=%i", status_kd_fan);   
 
      int status_salt=0;
      if (id(salt_lamps).state == "off") {
        status_salt=20;
      } else if (id(salt_lamps).state == "on") {
        status_salt=27;
      }
      id(disp1).send_command_printf("loungesalt_b.picc=%i", status_salt);
      id(disp1).send_command_printf("loungesalt_b.picc2=%i", status_salt);
      
      int status_vase=0;
      if (id(vase).state == "off") {
        status_vase=20;
      } else if (id(vase).state == "on") {
        status_vase=27;
      }
      id(disp1).send_command_printf("loungevase_b.picc=%i", status_vase);
      id(disp1).send_command_printf("loungevase_b.picc2=%i", status_vase);
      
      int status_patio=0;
      if (id(patio_door).state == "off") {
        status_patio=20;
      } else if (id(patio_door).state == "on") {
        status_patio=27;
      }
      id(disp1).send_command_printf("patio_b.picc=%i", status_patio);
      id(disp1).send_command_printf("patio_b.picc2=%i", status_patio);
      
      int status_dining_ceiling=0;
      if (id(dining_ceiling).state == "off") {
        status_dining_ceiling=20;
      } else if (id(dining_ceiling).state == "on") {
        status_dining_ceiling=27;
      }
      id(disp1).send_command_printf("diningmain_b.picc=%i", status_dining_ceiling);
      id(disp1).send_command_printf("diningmain_b.picc2=%i", status_dining_ceiling);
      
      int status_sideboard_lamp=0;
      if (id(sideboard_lamp).state == "off") {
        status_sideboard_lamp=20;
      } else if (id(sideboard_lamp).state == "on") {
        status_sideboard_lamp=27;
      }
      id(disp1).send_command_printf("sideboard_b.picc=%i", status_sideboard_lamp);
      id(disp1).send_command_printf("sideboard_b.picc2=%i", status_sideboard_lamp);
      
      int status_zb_4=0;
      if (id(zb_4).state == "off") {
        status_zb_4=20;
      } else if (id(zb_4).state == "on") {
        status_zb_4=27;
      }
      id(disp1).send_command_printf("biglamp_b.picc=%i", status_zb_4);
      id(disp1).send_command_printf("biglamp_b.picc2=%i", status_zb_4);
      
      int status_headboard=0;
      if (id(headboard).state == "off") {
        status_headboard=21;
      } else if (id(headboard).state == "on") {
        status_headboard=28;
      }
      id(disp1).send_command_printf("sharon_b.picc=%i", status_headboard);
      id(disp1).send_command_printf("sharon_b.picc2=%i", status_headboard);
      
      int status_br_lamp=0;
      if (id(br_lamp).state == "off") {
        status_br_lamp=21;
      } else if (id(br_lamp).state == "on") {
        status_br_lamp=28;
      }
      id(disp1).send_command_printf("andy_b.picc=%i", status_br_lamp);
      id(disp1).send_command_printf("andy_b.picc2=%i", status_br_lamp);
      
      int status_bedroom_ceiling=0;
      if (id(bedroom_ceiling).state == "off") {
        status_bedroom_ceiling=21;
      } else if (id(bedroom_ceiling).state == "on") {
        status_bedroom_ceiling=28;
      }
      id(disp1).send_command_printf("bedceil_b.picc=%i", status_bedroom_ceiling);
      id(disp1).send_command_printf("bedceil_b.picc2=%i", status_bedroom_ceiling);
      
      int status_dresser=0;
      if (id(dresser).state == "off") {
        status_dresser=21;
      } else if (id(dresser).state == "on") {
        status_dresser=28;
      }
      id(disp1).send_command_printf("dresser_b.picc=%i", status_dresser);
      id(disp1).send_command_printf("dresser_b.picc2=%i", status_dresser);
      
      
      int status_day=0;
      if (id(day_mode).state == "off") {
        status_day=16;
      } else if (id(day_mode).state == "on") {
        status_day=26;
      }
      id(disp1).send_command_printf("home.day_b.picc=%i", status_day);
      id(disp1).send_command_printf("home.day_b.picc2=%i", status_day);
      
      int status_evening=0;
      if (id(evening_mode).state == "off") {
        status_evening=16;
      } else if (id(evening_mode).state == "on") {
        status_evening=26;
      }
      id(disp1).send_command_printf("home.evening_b.picc=%i", status_evening);
      id(disp1).send_command_printf("home.evening_b.picc2=%i", status_evening);
      
      int status_night=0;
      if (id(night_mode).state == "off") {
        status_night=16;
      } else if (id(night_mode).state == "on") {
        status_night=26;
      }
      id(disp1).send_command_printf("home.night_b.picc=%i", status_night);
      id(disp1).send_command_printf("home.night_b.picc2=%i", status_night);
      
      int symbol=1;
      if (id(weather_symbol).state == "clear-night") {
        symbol=2;
      } else if (id(weather_symbol).state == "cloudy") {
        symbol=4;
        if (id(sun_sun).state == "below_horizon") {
          symbol=5;
        }
      } else if (id(weather_symbol).state == "fog") {
        symbol=7;
      } else if (id(weather_symbol).state == "hail" || id(weather_symbol).state == "snowy-rainy") {
        symbol=9;
      } else if (id(weather_symbol).state == "lightning") {
        symbol=10;
      } else if (id(weather_symbol).state == "lightning-rainy" || id(weather_symbol).state == "exceptional") {
        symbol=10;
        if (id(sun_sun).state == "below_horizon") {
          symbol=11;
        }
      } else if (id(weather_symbol).state == "partlycloudy") {
        symbol=13;
        if (id(sun_sun).state == "below_horizon") {
          symbol=5;
        }
      } else if (id(weather_symbol).state == "pouring") {
        symbol=8;
      } else if (id(weather_symbol).state == "rainy") {
        symbol=8;
      } else if (id(weather_symbol).state == "snowy") {
        symbol=9;
      } else if (id(weather_symbol).state == "sunny") {
        symbol=3;
      } else if (id(weather_symbol).state == "windy" || id(weather_symbol).state == "windy-variant") {
        symbol=5;              
      }
      id(disp1).send_command_printf("home.weather.pic=%i", symbol);
      id(disp1).send_command_printf("home.weather.pic2=%i", symbol);
      id(disp1).set_component_text_printf("tempoutside", "%.1f ", id(temp_outside).state);
      id(disp1).set_component_text_printf("living.lrt", "%.1f ", id(lr_ar_t).state);
      id(disp1).set_component_text_printf("living.lrh", "%.1f ", id(lr_ar_h).state);
      id(disp1).set_component_text_printf("living.lrv", "%.1f ", id(lr_ar_v).state);
      auto time_text = id(homeassistant_time).now().strftime("%I:%M%p");
      id(disp1).set_component_text("home.time", time_text.c_str());
      id(disp1).set_component_text_printf("weathersum", "%s", id(weather_symbol).state.c_str());
#      id(disp1).set_component_text_printf("weathersum", "%s", "new_weather";